import { Archive, Download, Plus, RotateCcw, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { api } from '../api';
import { ActionButton } from '../components/ui/ActionButton';
import { Modal } from '../components/ui/Modal';
import { EmptyState, Skeleton } from '../components/ui/States';
import { formatBytes, formatDate } from '../format';
import { useI18n } from '../i18n';
import type { Backup, Server } from '../types';

export function Backups({ server, notify, onError }: { server: Server; notify: (message: string, variant?: 'success' | 'error' | 'info' | 'warning') => void; onError: (error: unknown) => void }) {
  const { tr } = useI18n(); const [items, setItems] = useState<Backup[] | null>(null); const [busy, setBusy] = useState(false); const [createOpen, setCreateOpen] = useState(false); const [name, setName] = useState(''); const [confirm, setConfirm] = useState<{ action: 'restore' | 'delete'; item: Backup } | null>(null);
  const load = useCallback(() => api<Backup[]>(`/api/v1/servers/${server.id}/backups`).then(setItems).catch(onError), [onError, server.id]);
  useEffect(() => { load(); const timer = window.setInterval(load, 4000); return () => window.clearInterval(timer); }, [load]);
  const create = async () => { setBusy(true); try { await api(`/api/v1/servers/${server.id}/backups`, { method: 'POST', body: JSON.stringify({ name: name.trim() }) }); notify(tr('Backup masuk ke antrean.', 'Backup queued.'), 'success'); setCreateOpen(false); setName(''); await load(); } catch (error) { onError(error); } finally { setBusy(false); } };
  const runConfirmed = async () => { if (!confirm) return; setBusy(true); try { if (confirm.action === 'restore') await api(`/api/v1/servers/${server.id}/backups/${confirm.item.id}/restore`, { method: 'POST', body: '{}' }); else await api(`/api/v1/servers/${server.id}/backups/${confirm.item.id}`, { method: 'DELETE' }); notify(confirm.action === 'restore' ? tr('Snapshot pra-restore dan restore masuk antrean.', 'Pre-restore snapshot and restore queued.') : tr('Backup dihapus.', 'Backup deleted.'), 'success'); setConfirm(null); await load(); } catch (error) { onError(error); } finally { setBusy(false); } };
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">CHECKSUMMED ARCHIVES</p><h1>{tr('Backup', 'Backups')}</h1><p>{tr('Snapshot lokal terverifikasi untuk pemulihan world dan konfigurasi.', 'Verified local snapshots for world and configuration recovery.')}</p></div><ActionButton icon={Plus} disabled={!!server.currentJob} onClick={() => { setName(`Backup ${new Date().toLocaleString('id-ID')}`); setCreateOpen(true); }}>{tr('Buat Backup', 'Create Backup')}</ActionButton></div><section className="surface">{items === null ? <Skeleton lines={4} /> : items.length === 0 ? <EmptyState icon={Archive} title={tr('Belum ada backup', 'No backups yet')} description={tr('Buat backup sebelum mengganti plugin, mod, atau world.', 'Create a backup before changing plugins, mods, or worlds.')} action={{ label: tr('Buat Backup', 'Create Backup'), onClick: () => setCreateOpen(true) }} /> : <div className="data-list">{items.map((item) => <article key={item.id}><Archive /><div><b>{item.name}</b><small>{formatDate(item.createdAt)} · {formatBytes(item.sizeBytes)}{item.checksumSha256 ? ` · SHA-256 ${item.checksumSha256.slice(0, 12)}…` : ''}</small>{item.error && <em>{item.error}</em>}</div><span className={`data-status ${item.status}`}>{item.status}</span><div className="row-actions"><ActionButton size="sm" variant="ghost" icon={Download} disabled={item.status !== 'ready'} onClick={() => { window.location.href = `/api/v1/servers/${server.id}/backups/${item.id}/download`; }}>{tr('Unduh', 'Download')}</ActionButton><ActionButton size="sm" variant="ghost" icon={RotateCcw} disabled={item.status !== 'ready' || !item.checksumSha256 || !!server.currentJob} onClick={() => setConfirm({ action: 'restore', item })}>{tr('Restore', 'Restore')}</ActionButton><ActionButton size="sm" variant="ghost" icon={Trash2} disabled={!['ready', 'failed'].includes(item.status)} onClick={() => setConfirm({ action: 'delete', item })}>{tr('Hapus', 'Delete')}</ActionButton></div></article>)}</div>}</section>
    <Modal open={createOpen} onClose={() => setCreateOpen(false)} title={tr('Buat Backup', 'Create Backup')} footer={<><ActionButton variant="secondary" onClick={() => setCreateOpen(false)}>{tr('Batal', 'Cancel')}</ActionButton><ActionButton loading={busy} onClick={create}>{tr('Buat Backup', 'Create Backup')}</ActionButton></>}><label>{tr('Nama backup', 'Backup name')}<input value={name} onChange={(event) => setName(event.target.value)} maxLength={64} /></label></Modal>
    <Modal open={!!confirm} onClose={() => setConfirm(null)} title={confirm?.action === 'restore' ? tr('Restore backup?', 'Restore backup?') : tr('Hapus backup?', 'Delete backup?')} footer={<><ActionButton variant="secondary" onClick={() => setConfirm(null)}>{tr('Batal', 'Cancel')}</ActionButton><ActionButton variant={confirm?.action === 'delete' ? 'danger' : 'primary'} loading={busy} onClick={runConfirmed}>{tr('Konfirmasi', 'Confirm')}</ActionButton></>}><p>{confirm?.action === 'restore' ? tr('MyPanel akan membuat backup pra-restore, memverifikasi checksum arsip, lalu menghentikan server dan mengganti world saat ini.', 'MyPanel will create a pre-restore backup, verify the archive checksum, then stop the server and replace the current world.') : tr('Backup akan dihapus permanen.', 'The backup will be permanently deleted.')}</p></Modal>
  </div>;
}
