import { Archive, Boxes, Check, Cpu, HardDrive, MemoryStick, PackagePlus, RefreshCw, ShoppingCart } from 'lucide-react';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { api } from '../api';
import { ActionButton } from '../components/ui/ActionButton';
import { Modal } from '../components/ui/Modal';
import { EmptyState, Skeleton } from '../components/ui/States';
import { MetricBar } from '../components/ui/MetricBar';
import { useI18n } from '../i18n';
import { formatBytes, formatDate } from '../format';
import type { Capacity, HostingPackage, Order, PanelUser, Runtime, Subscription } from '../types';

const idr = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });

export function Marketplace({ catalog, reloadServers, notify, onError }: { catalog: Runtime[]; reloadServers: () => Promise<void>; notify: (message: string, variant?: 'success' | 'error' | 'info' | 'warning') => void; onError: (error: unknown) => void }) {
  const { tr } = useI18n(); const [packages, setPackages] = useState<HostingPackage[] | null>(null); const [capacity, setCapacity] = useState<Capacity | null>(null); const [selected, setSelected] = useState<HostingPackage | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(() => Promise.all([api<HostingPackage[]>('/api/v1/packages'), api<Capacity>('/api/v1/capacity')]).then(([p, c]) => { setPackages(p); setCapacity(c); }).catch(onError), [onError]);
  useEffect(() => { load(); }, [load]);
  const checkout = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected) return; setBusy(true); const data = new FormData(event.currentTarget); try { await api('/api/v1/checkout', { method: 'POST', body: JSON.stringify({ packageId: selected.id, idempotencyKey: crypto.randomUUID(), name: data.get('name'), runtime: data.get('runtime'), version: data.get('version'), javaVersion: Number(data.get('javaVersion')) }) }); notify(tr('Pembayaran simulasi berhasil dan provisioning dimulai.', 'Simulated payment succeeded and provisioning started.'), 'success'); setSelected(null); await Promise.all([load(), reloadServers()]); } catch (error) { onError(error); } finally { setBusy(false); } };
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">MARKETPLACE</p><h1>{tr('Beli Server', 'Buy a Server')}</h1><p>{tr('Pilih paket. Pembayaran hanya simulasi dan tidak memproses uang nyata.', 'Choose a package. Payment is simulated and never processes real money.')}</p></div></div>
    {packages === null ? <section className="surface"><Skeleton lines={4} /></section> : packages.length === 0 ? <section className="surface"><EmptyState icon={Boxes} title={tr('Belum ada paket aktif', 'No active packages')} description={tr('Administrator perlu mengaktifkan paket sebelum checkout tersedia.', 'An administrator must activate a package before checkout is available.')} /></section> : <div className="package-grid">{packages.map((item) => { const available = capacity?.packageAvailability[item.id] ?? false; return <article className={`surface package-card ${available ? '' : 'unavailable-card'}`} key={item.id}><div className="package-icon"><Boxes /></div><h2>{item.name}</h2><p>{item.description}</p><strong>{idr.format(item.priceIdr)}<small>/30 hari</small></strong><dl><div><Cpu /><dt>{item.cpu} vCPU</dt></div><div><MemoryStick /><dt>{formatBytes(item.memoryMb * 1024 * 1024)} RAM</dt></div><div><HardDrive /><dt>{formatBytes(item.diskMb * 1024 * 1024)} disk</dt></div></dl><ActionButton icon={ShoppingCart} disabled={!available} onClick={() => setSelected(item)}>{available ? tr('Pilih paket', 'Choose package') : tr('Kapasitas tidak cukup', 'Insufficient capacity')}</ActionButton></article>; })}</div>}
    <Modal open={!!selected} onClose={() => !busy && setSelected(null)} title={tr(`Checkout ${selected?.name ?? ''}`, `Checkout ${selected?.name ?? ''}`)}><form className="form-stack" onSubmit={checkout}><div className="simulated-payment"><Check /><span><b>{tr('Pembayaran simulasi instan', 'Instant simulated payment')}</b><small>{selected && idr.format(selected.priceIdr)} · 30 {tr('hari', 'days')}</small></span></div><label>{tr('Nama server', 'Server name')}<input name="name" required maxLength={48} /></label><div className="form-row"><label>Runtime<select name="runtime">{catalog.map((runtime) => <option key={runtime.id} value={runtime.id}>{runtime.name}</option>)}</select></label><label>Java<select name="javaVersion" defaultValue="21"><option value="21">Java 21</option><option value="25">Java 25</option></select></label></div><label>{tr('Versi Minecraft', 'Minecraft version')}<input name="version" defaultValue="1.21.4" required /></label><p className="form-note">{tr('Dengan konfirmasi, order simulasi langsung dibayar dan resource dicadangkan.', 'Confirmation immediately pays the simulated order and reserves resources.')}</p><ActionButton type="submit" loading={busy}>{tr('Bayar simulasi & buat server', 'Simulate payment & create server')}</ActionButton></form></Modal>
  </div>;
}

export function Billing({ notify, onError }: { notify: (message: string, variant?: 'success' | 'error' | 'info' | 'warning') => void; onError: (error: unknown) => void }) {
  const { tr } = useI18n(); const [orders, setOrders] = useState<Order[] | null>(null); const [subscriptions, setSubscriptions] = useState<Subscription[] | null>(null); const [busy, setBusy] = useState('');
  const load = useCallback(() => Promise.all([api<Order[]>('/api/v1/orders'), api<Subscription[]>('/api/v1/subscriptions')]).then(([o, s]) => { setOrders(o); setSubscriptions(s); }).catch(onError), [onError]); useEffect(() => { load(); }, [load]);
  const renew = async (item: Subscription) => { setBusy(item.id); try { const retry = item.status === 'action_required'; await api(`/api/v1/subscriptions/${item.id}/${retry ? 'retry' : 'renew'}`, { method: 'POST', body: JSON.stringify(retry ? {} : { idempotencyKey: crypto.randomUUID() }) }); notify(retry ? tr('Provisioning dicoba kembali.', 'Provisioning retry queued.') : tr('Langganan diperpanjang 30 hari.', 'Subscription renewed for 30 days.'), 'success'); await load(); } catch (error) { onError(error); } finally { setBusy(''); } };
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">SIMULATED BILLING</p><h1>{tr('Pesanan & Langganan', 'Orders & Subscriptions')}</h1><p>{tr('Seluruh transaksi di halaman ini adalah simulasi.', 'Every transaction on this page is simulated.')}</p></div></div>
    <section className="surface"><div className="section-heading"><div><h2>{tr('Langganan', 'Subscriptions')}</h2><p>{tr('Masa aktif dan status server', 'Server periods and status')}</p></div></div>{subscriptions === null ? <Skeleton lines={3} /> : subscriptions.length === 0 ? <EmptyState icon={RefreshCw} title={tr('Belum ada langganan', 'No subscriptions yet')} description={tr('Beli paket untuk membuat langganan pertama.', 'Buy a package to create your first subscription.')} /> : <div className="data-table hosting-table">{subscriptions.map((item) => { const retry = item.status === 'action_required'; const released = item.status === 'released'; const actionable = retry || item.status === 'active' || item.status === 'grace' || released; const statusNote = item.status === 'grace' ? tr(`Masa tenggang sampai ${formatDate(item.graceEndsAt)}`, `Grace period until ${formatDate(item.graceEndsAt)}`) : released ? tr('Resource komputasi dilepas; data tetap disimpan.', 'Compute resources released; data is retained.') : `${item.status} · ${tr('berakhir', 'ends')} ${formatDate(item.currentPeriodEnd)}`; return <article key={item.id}><div><b>{item.packageName}</b><small>{statusNote}</small></div><span>{item.cpu} vCPU · {formatBytes(item.memoryMb * 1024 * 1024)}</span>{actionable && <ActionButton size="sm" loading={busy === item.id} onClick={() => renew(item)}>{retry ? tr('Coba lagi', 'Retry') : released ? tr('Aktifkan lagi', 'Reactivate') : tr('Perpanjang', 'Renew')}</ActionButton>}</article>; })}</div>}</section>
    <section className="surface"><div className="section-heading"><div><h2>{tr('Riwayat Pesanan', 'Order History')}</h2><p>{tr('Bukti transaksi simulasi', 'Simulated transaction records')}</p></div></div>{orders === null ? <Skeleton lines={4} /> : orders.length === 0 ? <EmptyState icon={ShoppingCart} title={tr('Belum ada pesanan', 'No orders yet')} description={tr('Pesanan muncul setelah checkout.', 'Orders appear after checkout.')} /> : <div className="data-table hosting-table">{orders.map((item) => <article key={item.id}><div><b>{item.packageName} · {idr.format(item.amountIdr)}</b><small>{item.paymentReference} · {formatDate(item.createdAt)}</small></div><span>{item.kind} · {item.status}</span></article>)}</div>}</section>
  </div>;
}

export function AdminUsers({ notify, onError }: { notify: (message: string, variant?: 'success' | 'error' | 'info' | 'warning') => void; onError: (error: unknown) => void }) {
  const { tr } = useI18n(); const [items, setItems] = useState<PanelUser[] | null>(null); const [resetUser, setResetUser] = useState<PanelUser | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(() => api<PanelUser[]>('/api/v1/admin/users').then(setItems).catch(onError), [onError]); useEffect(() => { load(); }, [load]);
  const status = async (item: PanelUser) => { setBusy(true); try { await api(`/api/v1/admin/users/${item.id}/status`, { method: 'PUT', body: JSON.stringify({ status: item.status === 'active' ? 'suspended' : 'active' }) }); notify(tr('Status akun diperbarui.', 'Account status updated.'), 'success'); await load(); } catch (error) { onError(error); } finally { setBusy(false); } };
  const reset = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!resetUser) return; setBusy(true); const data = new FormData(event.currentTarget); try { await api(`/api/v1/admin/users/${resetUser.id}/reset-password`, { method: 'POST', body: JSON.stringify({ password: data.get('password') }) }); notify(tr('Password sementara ditetapkan; session lama dibatalkan.', 'Temporary password set; previous sessions invalidated.'), 'success'); setResetUser(null); await load(); } catch (error) { onError(error); } finally { setBusy(false); } };
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">ADMIN</p><h1>{tr('Akun User', 'User Accounts')}</h1><p>{tr('Kelola akses tanpa melihat password user.', 'Manage access without viewing user passwords.')}</p></div></div><section className="surface">{items === null ? <Skeleton lines={5} /> : <div className="data-table hosting-table">{items.map((item) => <article key={item.id}><div><b>{item.username}</b><small>{item.id} · {item.role} · {item.status}</small></div>{item.role === 'user' && <div className="row-actions"><ActionButton size="sm" variant="secondary" onClick={() => setResetUser(item)}>{tr('Reset password', 'Reset password')}</ActionButton><ActionButton size="sm" variant={item.status === 'active' ? 'danger' : 'primary'} loading={busy} onClick={() => status(item)}>{item.status === 'active' ? tr('Suspend', 'Suspend') : tr('Aktifkan', 'Activate')}</ActionButton></div>}</article>)}</div>}</section><Modal open={!!resetUser} onClose={() => setResetUser(null)} title={tr(`Reset password ${resetUser?.username ?? ''}`, `Reset ${resetUser?.username ?? ''} password`)}><form className="form-stack" onSubmit={reset}><label>{tr('Password sementara', 'Temporary password')}<input name="password" type="password" minLength={12} required autoComplete="new-password" /></label><p className="form-note">{tr('User diwajibkan mengganti password setelah login.', 'The user must change this password after signing in.')}</p><ActionButton type="submit" loading={busy}>{tr('Tetapkan password', 'Set password')}</ActionButton></form></Modal></div>;
}

export function AdminPackages({ notify, onError }: { notify: (message: string, variant?: 'success' | 'error' | 'info' | 'warning') => void; onError: (error: unknown) => void }) {
  const { tr } = useI18n(); const [items, setItems] = useState<HostingPackage[] | null>(null); const [editing, setEditing] = useState<HostingPackage | 'new' | null>(null); const [busy, setBusy] = useState(false); const load = useCallback(() => api<HostingPackage[]>('/api/v1/packages?all=1').then(setItems).catch(onError), [onError]); useEffect(() => { load(); }, [load]);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const body = { slug: data.get('slug'), name: data.get('name'), description: data.get('description'), priceIdr: Number(data.get('price')), cpu: Number(data.get('cpu')), memoryMb: Number(data.get('memory')), diskMb: Number(data.get('disk')), sortOrder: Number(data.get('sort')), active: data.get('active') === 'on' }; setBusy(true); try { await api(editing === 'new' ? '/api/v1/packages' : `/api/v1/packages/${(editing as HostingPackage).id}`, { method: editing === 'new' ? 'POST' : 'PUT', body: JSON.stringify(body) }); notify(tr('Paket disimpan.', 'Package saved.'), 'success'); setEditing(null); await load(); } catch (error) { onError(error); } finally { setBusy(false); } };
  const archive = async (item: HostingPackage) => { setBusy(true); try { await api(`/api/v1/packages/${item.id}`, { method: 'DELETE' }); notify(tr('Paket diarsipkan.', 'Package archived.'), 'success'); await load(); } catch (error) { onError(error); } finally { setBusy(false); } };
  const value = editing === 'new' ? null : editing;
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">ADMIN</p><h1>{tr('Paket Hosting', 'Hosting Packages')}</h1><p>{tr('Perubahan hanya berlaku pada checkout baru.', 'Changes apply only to new checkouts.')}</p></div><ActionButton icon={PackagePlus} onClick={() => setEditing('new')}>{tr('Paket baru', 'New package')}</ActionButton></div><section className="surface">{items === null ? <Skeleton lines={5} /> : <div className="data-table hosting-table">{items.map((item) => <article key={item.id}><div><b>{item.name} · {idr.format(item.priceIdr)}</b><small>{item.slug} · {item.cpu} vCPU · {formatBytes(item.memoryMb * 1024 * 1024)} · {item.active ? 'active' : 'archived'}</small></div><div className="row-actions"><ActionButton size="sm" variant="secondary" onClick={() => setEditing(item)}>{tr('Edit', 'Edit')}</ActionButton>{item.active && <ActionButton size="sm" variant="danger" icon={Archive} loading={busy} onClick={() => archive(item)}>{tr('Arsip', 'Archive')}</ActionButton>}</div></article>)}</div>}</section><Modal open={!!editing} onClose={() => setEditing(null)} title={editing === 'new' ? tr('Paket baru', 'New package') : tr('Edit paket', 'Edit package')}><form className="form-stack" onSubmit={save}><div className="form-row"><label>Slug<input name="slug" defaultValue={value?.slug} required pattern="[A-Za-z0-9_.-]{3,32}" /></label><label>{tr('Nama', 'Name')}<input name="name" defaultValue={value?.name} required maxLength={64} /></label></div><label>{tr('Deskripsi', 'Description')}<textarea name="description" defaultValue={value?.description} maxLength={500} /></label><div className="form-row"><label>{tr('Harga IDR', 'Price IDR')}<input name="price" type="number" min="0" defaultValue={value?.priceIdr ?? 29000} required /></label><label>vCPU<input name="cpu" type="number" min="1" max="32" defaultValue={value?.cpu ?? 1} required /></label></div><div className="form-row"><label>RAM MiB<input name="memory" type="number" min="1024" defaultValue={value?.memoryMb ?? 1024} required /></label><label>Disk MiB<input name="disk" type="number" min="1024" defaultValue={value?.diskMb ?? 10240} required /></label></div><div className="form-row"><label>Sort<input name="sort" type="number" defaultValue={value?.sortOrder ?? 10} /></label><label className="checkbox-row"><input name="active" type="checkbox" defaultChecked={value?.active ?? true} />Active</label></div><ActionButton type="submit" loading={busy}>{tr('Simpan paket', 'Save package')}</ActionButton></form></Modal></div>;
}

export function AdminCapacity({ onError }: { onError: (error: unknown) => void }) {
  const { tr } = useI18n(); const [capacity, setCapacity] = useState<Capacity | null>(null); useEffect(() => { api<Capacity>('/api/v1/capacity').then(setCapacity).catch(onError); }, [onError]); if (!capacity?.total || !capacity.reserved) return <section className="surface"><Skeleton lines={5} /></section>;
  const { total, reserved, available } = capacity; return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">ADMIN</p><h1>{tr('Kapasitas Node', 'Node Capacity')}</h1><p>{tr('Kapasitas jual menentukan apakah checkout dapat diterima.', 'Sellable capacity determines whether checkout can be accepted.')}</p></div></div><section className="surface capacity-panel"><MetricBar label="vCPU" value={reserved.cpu} max={total.cpu} unit="" detail={`${available.cpu} vCPU ${tr('tersisa', 'remaining')}`} /><MetricBar label="RAM" value={reserved.memoryMb} max={total.memoryMb} unit=" MiB" detail={`${formatBytes(available.memoryMb * 1024 * 1024)} ${tr('tersisa', 'remaining')}`} /><MetricBar label="Disk" value={reserved.diskMb} max={total.diskMb} unit=" MiB" detail={`${formatBytes(available.diskMb * 1024 * 1024)} ${tr('tersisa', 'remaining')}`} /><MetricBar label="Port" value={reserved.ports} max={total.ports} unit="" detail={`${available.ports} ${tr('tersisa', 'remaining')}`} />{capacity.host && <div className="host-facts"><span><Cpu />{capacity.host.cpu} CPU host</span><span><MemoryStick />{formatBytes(capacity.host.memoryAvailableBytes)} RAM available</span><span><HardDrive />{formatBytes(capacity.host.diskAvailableBytes)} disk available</span></div>}</section></div>;
}
