import { CalendarClock, Plus, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { api } from '../api';
import { ActionButton } from '../components/ui/ActionButton';
import { EmptyState, Skeleton } from '../components/ui/States';
import { Modal } from '../components/ui/Modal';
import { useI18n } from '../i18n';
import { formatDate } from '../format';
import type { Schedule, Server } from '../types';

export function Schedules({ server, notify, onError }: { server: Server; notify: (message: string, variant?: 'success' | 'error' | 'info' | 'warning') => void; onError: (error: unknown) => void }) {
  const { tr } = useI18n(); const [items, setItems] = useState<Schedule[] | null>(null); const [busy, setBusy] = useState(false); const [open, setOpen] = useState(false); const [action, setAction] = useState('restart');
  const load = useCallback(() => api<Schedule[]>(`/api/v1/servers/${server.id}/schedules`).then(setItems).catch(onError), [onError, server.id]);
  useEffect(() => { load(); }, [load]);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); try { await api(`/api/v1/servers/${server.id}/schedules`, { method: 'POST', body: JSON.stringify({ name: data.get('name'), action, intervalMinutes: Number(data.get('interval')), payload: action === 'command' ? { command: data.get('command') } : {} }) }); notify(tr('Jadwal dibuat.', 'Schedule created.'), 'success'); setOpen(false); await load(); } catch (error) { onError(error); } finally { setBusy(false); } };
  const remove = async (id: string) => { setBusy(true); try { await api(`/api/v1/servers/${server.id}/schedules/${id}`, { method: 'DELETE' }); notify(tr('Jadwal dihapus.', 'Schedule deleted.'), 'success'); await load(); } catch (error) { onError(error); } finally { setBusy(false); } };
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">AUTOMATION</p><h1>{tr('Jadwal', 'Schedules')}</h1><p>{tr('Jalankan lifecycle, backup, dan command secara berkala.', 'Run lifecycle actions, backups, and commands on an interval.')}</p></div><ActionButton icon={Plus} onClick={() => setOpen(true)}>{tr('Jadwal Baru', 'New Schedule')}</ActionButton></div><section className="surface">{items === null ? <Skeleton lines={4} /> : items.length === 0 ? <EmptyState icon={CalendarClock} title={tr('Belum ada jadwal', 'No schedules yet')} description={tr('Otomatiskan restart, backup, atau command rutin.', 'Automate restarts, backups, or recurring commands.')} action={{ label: tr('Buat Jadwal', 'Create Schedule'), onClick: () => setOpen(true) }} /> : <div className="data-list">{items.map((item) => <article key={item.id}><CalendarClock /><div><b>{item.name}</b><small>{item.action} · {tr('setiap', 'every')} {item.intervalMinutes} {tr('menit', 'minutes')} · {formatDate(item.nextRunAt)}</small></div><span className={`data-status ${item.enabled ? 'ready' : ''}`}>{item.enabled ? tr('Aktif', 'Active') : tr('Nonaktif', 'Disabled')}</span><div className="row-actions"><ActionButton size="sm" variant="ghost" icon={Trash2} loading={busy} onClick={() => remove(item.id)}>{tr('Hapus', 'Delete')}</ActionButton></div></article>)}</div>}</section>
    <Modal open={open} onClose={() => setOpen(false)} title={tr('Jadwal Baru', 'New Schedule')}><form className="form-stack" onSubmit={create}><label>{tr('Nama', 'Name')}<input name="name" required maxLength={64} placeholder={tr('Backup harian', 'Daily backup')} /></label><label>{tr('Aksi', 'Action')}<select value={action} onChange={(event) => setAction(event.target.value)}><option value="restart">Restart</option><option value="backup">Backup</option><option value="start">Start</option><option value="stop">Stop</option><option value="command">Command</option></select></label>{action === 'command' && <label>Command<input name="command" required placeholder="say Restart in 5 minutes" /></label>}<label>Interval<input name="interval" type="number" min="1" max="525600" defaultValue="1440" required /><small>{tr('menit', 'minutes')}</small></label><ActionButton type="submit" loading={busy}>{tr('Simpan Jadwal', 'Save Schedule')}</ActionButton></form></Modal>
  </div>;
}
