import { CalendarClock, Edit3, Pause, Play, Plus, Trash2, Zap } from 'lucide-react';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { api } from '../api';
import { ActionButton } from '../components/ui/ActionButton';
import { Modal } from '../components/ui/Modal';
import { EmptyState, Skeleton } from '../components/ui/States';
import { formatDate } from '../format';
import { useI18n } from '../i18n';
import type { Schedule, Server } from '../types';

export function Schedules({ server, notify, onError }: { server: Server; notify: (message: string, variant?: 'success' | 'error' | 'info' | 'warning') => void; onError: (error: unknown) => void }) {
  const { tr } = useI18n(); const [items, setItems] = useState<Schedule[] | null>(null); const [busy, setBusy] = useState(''); const [editor, setEditor] = useState<Schedule | 'new' | null>(null); const [action, setAction] = useState('restart'); const [removeTarget, setRemoveTarget] = useState<Schedule | null>(null);
  const load = useCallback(() => api<Schedule[]>(`/api/v1/servers/${server.id}/schedules`).then(setItems).catch(onError), [onError, server.id]);
  useEffect(() => { load(); }, [load]);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const payload = action === 'command' ? { command: data.get('command') } : {}; const body = JSON.stringify({ name: data.get('name'), action, intervalMinutes: Number(data.get('interval')), payload, enabled: editor === 'new' ? true : editor?.enabled }); setBusy('save'); try { await api(editor === 'new' ? `/api/v1/servers/${server.id}/schedules` : `/api/v1/servers/${server.id}/schedules/${editor?.id}`, { method: editor === 'new' ? 'POST' : 'PUT', body }); notify(editor === 'new' ? tr('Jadwal dibuat.', 'Schedule created.') : tr('Jadwal diperbarui.', 'Schedule updated.'), 'success'); setEditor(null); await load(); } catch (error) { onError(error); } finally { setBusy(''); } };
  const updateEnabled = async (item: Schedule) => { setBusy(item.id); try { await api(`/api/v1/servers/${server.id}/schedules/${item.id}`, { method: 'PUT', body: JSON.stringify({ ...item, enabled: !item.enabled }) }); notify(item.enabled ? tr('Jadwal dinonaktifkan.', 'Schedule disabled.') : tr('Jadwal diaktifkan.', 'Schedule enabled.'), 'success'); await load(); } catch (error) { onError(error); } finally { setBusy(''); } };
  const runNow = async (item: Schedule) => { setBusy(item.id); try { await api(`/api/v1/servers/${server.id}/schedules/${item.id}/run`, { method: 'POST', body: '{}' }); notify(tr('Jadwal dijalankan sekarang.', 'Schedule queued to run now.'), 'success'); await load(); } catch (error) { onError(error); } finally { setBusy(''); } };
  const remove = async () => { if (!removeTarget) return; setBusy(removeTarget.id); try { await api(`/api/v1/servers/${server.id}/schedules/${removeTarget.id}`, { method: 'DELETE' }); notify(tr('Jadwal dihapus.', 'Schedule deleted.'), 'success'); setRemoveTarget(null); await load(); } catch (error) { onError(error); } finally { setBusy(''); } };
  const openEditor = (item: Schedule | 'new') => { setAction(item === 'new' ? 'restart' : item.action); setEditor(item); };
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">AUTOMATION</p><h1>{tr('Jadwal', 'Schedules')}</h1><p>{tr('Jalankan lifecycle, backup, dan command secara berkala.', 'Run lifecycle actions, backups, and commands on an interval.')}</p></div><ActionButton icon={Plus} onClick={() => openEditor('new')}>{tr('Jadwal Baru', 'New Schedule')}</ActionButton></div><section className="surface">{items === null ? <Skeleton lines={4} /> : items.length === 0 ? <EmptyState icon={CalendarClock} title={tr('Belum ada jadwal', 'No schedules yet')} description={tr('Otomatiskan restart, backup, atau command rutin.', 'Automate restarts, backups, or recurring commands.')} action={{ label: tr('Buat Jadwal', 'Create Schedule'), onClick: () => openEditor('new') }} /> : <div className="data-list schedule-list">{items.map((item) => <article key={item.id}><CalendarClock /><div><b>{item.name}</b><small>{item.action} · {tr('setiap', 'every')} {item.intervalMinutes} {tr('menit', 'minutes')} · {tr('berikutnya', 'next')} {formatDate(item.nextRunAt)}</small>{item.lastRunAt && <small>{tr('Terakhir', 'Last run')}: {formatDate(item.lastRunAt)}{item.lastJobId ? ` · job ${item.lastJobId.slice(0, 8)}` : ''}</small>}</div><span className={`data-status ${item.enabled ? 'ready' : ''}`}>{item.enabled ? tr('Aktif', 'Active') : tr('Nonaktif', 'Disabled')}</span><div className="row-actions"><ActionButton size="sm" variant="ghost" icon={Zap} loading={busy === item.id} disabled={!!server.currentJob} onClick={() => runNow(item)}>{tr('Jalankan', 'Run now')}</ActionButton><ActionButton size="sm" variant="ghost" icon={item.enabled ? Pause : Play} onClick={() => updateEnabled(item)}>{item.enabled ? tr('Jeda', 'Disable') : tr('Aktifkan', 'Enable')}</ActionButton><ActionButton size="sm" variant="ghost" icon={Edit3} onClick={() => openEditor(item)}>{tr('Edit', 'Edit')}</ActionButton><ActionButton size="sm" variant="ghost" icon={Trash2} onClick={() => setRemoveTarget(item)}>{tr('Hapus', 'Delete')}</ActionButton></div></article>)}</div>}</section>
    <Modal open={editor !== null} onClose={() => setEditor(null)} title={editor === 'new' ? tr('Jadwal Baru', 'New Schedule') : tr('Edit Jadwal', 'Edit Schedule')}><form className="form-stack" onSubmit={save}><label>{tr('Nama', 'Name')}<input name="name" required maxLength={64} defaultValue={editor === 'new' ? '' : editor?.name} placeholder={tr('Backup harian', 'Daily backup')} /></label><label>{tr('Aksi', 'Action')}<select value={action} onChange={(event) => setAction(event.target.value)}><option value="restart">Restart</option><option value="backup">Backup</option><option value="start">Start</option><option value="stop">Stop</option><option value="command">Command</option></select></label>{action === 'command' && <label>Command<input name="command" required defaultValue={editor !== 'new' ? String(editor?.payload.command ?? '') : ''} placeholder="say Restart in 5 minutes" /></label>}<label>Interval<input name="interval" type="number" min="1" max="525600" defaultValue={editor === 'new' ? 1440 : editor?.intervalMinutes} required /><small>{tr('menit', 'minutes')}</small></label>{action === 'backup' && <p className="form-note">{tr('MyPanel menyimpan tujuh backup terbaru dari jadwal ini.', 'MyPanel retains the seven newest backups from this schedule.')}</p>}<ActionButton type="submit" loading={busy === 'save'}>{tr('Simpan Jadwal', 'Save Schedule')}</ActionButton></form></Modal>
    <Modal open={!!removeTarget} onClose={() => setRemoveTarget(null)} title={tr('Hapus jadwal?', 'Delete schedule?')} footer={<><ActionButton variant="secondary" onClick={() => setRemoveTarget(null)}>{tr('Batal', 'Cancel')}</ActionButton><ActionButton variant="danger" loading={!!removeTarget && busy === removeTarget.id} onClick={remove}>{tr('Hapus', 'Delete')}</ActionButton></>}><p>{tr(`Jadwal “${removeTarget?.name ?? ''}” tidak akan dijalankan lagi.`, `“${removeTarget?.name ?? ''}” will no longer run.`)}</p></Modal>
  </div>;
}
