import { AlertTriangle, Cpu, HardDrive, MemoryStick, Save, Server as ServerIcon, Settings2, Trash2, Zap } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../api';
import { ActionButton } from '../components/ui/ActionButton';
import { Modal } from '../components/ui/Modal';
import { useI18n } from '../i18n';
import { formatBytes } from '../format';
import type { ActionResponse, Server } from '../types';

type SettingsTab = 'general' | 'startup' | 'limits' | 'danger';

export function ServerSettings({ server, reload, notify, onError, remove }: { server: Server; reload: () => Promise<void>; notify: (message: string, variant?: 'success' | 'error' | 'info' | 'warning') => void; onError: (error: unknown) => void; remove: (server: Server, purge: boolean) => Promise<void> }) {
  const { tr } = useI18n(); const [tab, setTabUnsafe] = useState<SettingsTab>('general'); const [busy, setBusy] = useState(false); const [confirm, setConfirm] = useState<{ purge: boolean } | null>(null); const [typed, setTyped] = useState(''); const [dirty, setDirty] = useState(false);
  const config = server.config ?? {};
  const setTab = (next: SettingsTab) => { if (dirty && !window.confirm(tr('Buang perubahan yang belum disimpan?', 'Discard unsaved changes?'))) return; setDirty(false); setTabUnsafe(next); };
  useEffect(() => { if (!dirty) return; const warn = (event: BeforeUnloadEvent) => event.preventDefault(); window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  useEffect(() => { const changed = (event: Event) => { if (event.target instanceof Element && event.target.closest('.settings-content form')) setDirty(true); }; document.addEventListener('input', changed); document.addEventListener('change', changed); return () => { document.removeEventListener('input', changed); document.removeEventListener('change', changed); }; }, []);
  const save = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true); setDirty(false); const data = new FormData(event.currentTarget);
    try { await api<ActionResponse>(`/api/v1/servers/${server.id}/config`, { method: 'PUT', body: JSON.stringify({ ...config, motd: data.get('motd'), difficulty: data.get('difficulty'), gamemode: data.get('gamemode'), maxPlayers: Number(data.get('maxPlayers')), viewDistance: Number(data.get('viewDistance')), simulationDistance: Number(data.get('simulationDistance')), onlineMode: data.get('onlineMode') === 'on', whiteList: data.get('whiteList') === 'on', whiteListPlayers: data.get('whiteListPlayers') }) }); notify(tr('Konfigurasi masuk antrean dan akan diterapkan.', 'Configuration queued and will be applied.'), 'success'); await reload(); }
    catch (error) { setDirty(true); onError(error); } finally { setBusy(false); }
  };
  const saveStartup = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true); setDirty(false); const data = new FormData(event.currentTarget);
    try { await api<ActionResponse>(`/api/v1/servers/${server.id}/config`, { method: 'PUT', body: JSON.stringify({ ...config, jvmOpts: String(data.get('jvmOpts') ?? '').trim(), extraArgs: String(data.get('extraArgs') ?? '').trim() }) }); notify(tr('Perintah startup masuk antrean dan akan diterapkan saat container dibuat ulang.', 'Startup command queued and will apply when the container is recreated.'), 'success'); await reload(); }
    catch (error) { setDirty(true); onError(error); } finally { setBusy(false); }
  };
  const tabs: Array<{ id: SettingsTab; label: string; icon: typeof Settings2 }> = [{ id: 'general', label: tr('Umum', 'General'), icon: Settings2 }, { id: 'startup', label: tr('Startup', 'Startup'), icon: Zap }, { id: 'limits', label: tr('Batas Resource', 'Limits'), icon: Cpu }, { id: 'danger', label: tr('Zona Bahaya', 'Danger Zone'), icon: AlertTriangle }];
  return <div className="settings-layout"><nav className="settings-tabs">{tabs.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}><Icon />{label}</button>)}</nav><section key={server.updatedAt} className={`surface settings-content ${tab === 'danger' ? 'danger-zone' : ''}`}>
    {tab === 'general' && <form className="form-stack" onSubmit={save}><div className="section-heading"><div><h1>{tr('Pengaturan Umum', 'General Settings')}</h1><p>server.properties</p></div></div><div className="read-only-grid"><label>{tr('Nama Server', 'Server Name')}<input value={server.name} readOnly /><small>{tr('Perubahan nama belum didukung API.', 'Name updates are not supported by the API yet.')}</small></label><label>{tr('Versi Minecraft', 'Minecraft Version')}<input value={server.version} readOnly /></label></div><label>MOTD<input name="motd" defaultValue={String(config.motd ?? 'A MyPanel Minecraft Server')} /></label><div className="form-row"><label>Difficulty<select name="difficulty" defaultValue={String(config.difficulty ?? 'normal')}><option>peaceful</option><option>easy</option><option>normal</option><option>hard</option></select></label><label>Gamemode<select name="gamemode" defaultValue={String(config.gamemode ?? 'survival')}><option>survival</option><option>creative</option><option>adventure</option><option>spectator</option></select></label></div><div className="form-row"><label>Max players<input name="maxPlayers" type="number" min="1" max="1000" defaultValue={Number(config.maxPlayers ?? 20)} /></label><label>View distance<input name="viewDistance" type="number" min="2" max="32" defaultValue={Number(config.viewDistance ?? 10)} /></label></div><label>Simulation distance<input name="simulationDistance" type="number" min="2" max="32" defaultValue={Number(config.simulationDistance ?? 10)} /></label><div className="check-row"><label><input name="onlineMode" type="checkbox" defaultChecked={config.onlineMode !== false} />Online mode</label><label><input name="whiteList" type="checkbox" defaultChecked={config.whiteList === true} />Whitelist</label></div><label>Whitelist players<input name="whiteListPlayers" defaultValue={String(config.whiteListPlayers ?? '')} placeholder="Steve, Alex" /></label><ActionButton type="submit" icon={Save} loading={busy} disabled={!!server.currentJob}>{tr('Simpan dan Terapkan', 'Save and Apply')}</ActionButton></form>}
    {tab === 'startup' && <form className="form-stack settings-section" onSubmit={saveStartup}><h1>Startup</h1><p>{tr('Atur opsi JVM dan argumen server. MyPanel tetap mengelola executable Java, file JAR, memory limit, dan image runtime.', 'Configure JVM options and server arguments. MyPanel continues to manage the Java executable, JAR file, memory limit, and runtime image.')}</p><div className="detail-list"><div><ServerIcon /><span><small>Runtime</small><b>{server.runtime} · Java {server.javaVersion} · Minecraft {server.version}</b></span></div></div><label>{tr('Perintah yang dikelola', 'Managed command')}<input aria-label={tr('Perintah yang dikelola', 'Managed command')} value={`java ${String(config.jvmOpts ?? '')} -jar <managed-${server.runtime}.jar> ${String(config.extraArgs ?? '')}`.replace(/\s+/g, ' ').trim()} readOnly /></label><label>JVM options<input aria-label="JVM options" name="jvmOpts" maxLength={512} defaultValue={String(config.jvmOpts ?? '')} placeholder="-XX:+UseG1GC -XX:MaxGCPauseMillis=200" /><small>{tr('Gunakan flag JVM tanpa shell operator, kutip, atau argfile.', 'Use JVM flags without shell operators, quotes, or argument files.')}</small></label><label>{tr('Argumen server', 'Server arguments')}<input aria-label={tr('Argumen server', 'Server arguments')} name="extraArgs" maxLength={512} defaultValue={String(config.extraArgs ?? '')} placeholder="nogui" /></label><p className="form-note">{tr('Menyimpan akan membuat ulang container dan mempertahankan seluruh file di /data. Server akan berada dalam keadaan berhenti setelah update.', 'Saving recreates the container while preserving every file in /data. The server will remain stopped after the update.')}</p><ActionButton type="submit" icon={Save} loading={busy} disabled={!!server.currentJob}>{tr('Simpan Startup', 'Save Startup')}</ActionButton></form>}
    {tab === 'limits' && <div className="settings-section"><h1>{tr('Batas Resource', 'Resource Limits')}</h1><p>{tr('Nilai ini diterapkan oleh agent. Endpoint untuk mengubah limit belum tersedia.', 'These values are enforced by the agent. A limit-update endpoint is not available yet.')}</p><div className="limit-cards"><article><Cpu /><span><small>CPU</small><b>{server.cpu} vCPU</b></span></article><article><MemoryStick /><span><small>RAM</small><b>{formatBytes(server.memoryMb * 1024 * 1024)}</b></span></article><article><HardDrive /><span><small>Disk</small><b>{formatBytes(server.diskMb * 1024 * 1024)}</b></span></article></div></div>}
    {tab === 'danger' && <div className="settings-section"><AlertTriangle className="danger-icon" /><h1>{tr('Zona Bahaya', 'Danger Zone')}</h1><p>{tr('Penghapusan runtime membebaskan port. Data dapat dipertahankan untuk pemulihan manual atau dihapus permanen.', 'Deleting the runtime releases its port. Data can be retained for manual recovery or permanently removed.')}</p><div className="danger-actions"><div><b>{tr('Hapus runtime', 'Delete runtime')}</b><small>{tr('Pertahankan world dan file server.', 'Keep the server world and files.')}</small><ActionButton variant="danger" icon={Trash2} disabled={!!server.currentJob} onClick={() => setConfirm({ purge: false })}>{tr('Hapus, pertahankan data', 'Delete, retain data')}</ActionButton></div><div><b>{tr('Hapus seluruh data', 'Delete all data')}</b><small>{tr('World, konfigurasi, dan file akan hilang permanen.', 'World, configuration, and files will be permanently removed.')}</small><ActionButton variant="danger" icon={Trash2} disabled={!!server.currentJob} onClick={() => setConfirm({ purge: true })}>{tr('Hapus permanen', 'Delete permanently')}</ActionButton></div></div></div>}
  </section><Modal open={!!confirm} onClose={() => { setConfirm(null); setTyped(''); }} title={confirm?.purge ? tr('Hapus seluruh data?', 'Delete all data?') : tr('Hapus server?', 'Delete server?')} footer={<><ActionButton variant="secondary" onClick={() => setConfirm(null)}>{tr('Batal', 'Cancel')}</ActionButton><ActionButton variant="danger" loading={busy} disabled={typed !== server.name} onClick={async () => { if (!confirm) return; setBusy(true); try { await remove(server, confirm.purge); setConfirm(null); } finally { setBusy(false); } }}>{tr('Konfirmasi Hapus', 'Confirm Delete')}</ActionButton></>}><p>{tr(`Ketik nama server “${server.name}” untuk melanjutkan.`, `Type the server name “${server.name}” to continue.`)}</p><label>{tr('Nama server', 'Server name')}<input value={typed} onChange={(event) => setTyped(event.target.value)} autoComplete="off" /></label></Modal></div>;
}
