import { AlertTriangle, Cpu, HardDrive, MemoryStick, Save, Server as ServerIcon, Settings2, Trash2, Zap } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { api } from '../api';
import { ActionButton } from '../components/ui/ActionButton';
import { Modal } from '../components/ui/Modal';
import { useI18n } from '../i18n';
import { formatBytes } from '../format';
import type { ActionResponse, Server } from '../types';

type SettingsTab = 'general' | 'startup' | 'limits' | 'danger';

export function ServerSettings({ server, reload, notify, onError, remove }: { server: Server; reload: () => Promise<void>; notify: (message: string, variant?: 'success' | 'error' | 'info' | 'warning') => void; onError: (error: unknown) => void; remove: (server: Server, purge: boolean) => Promise<void> }) {
  const { tr } = useI18n(); const [tab, setTab] = useState<SettingsTab>('general'); const [busy, setBusy] = useState(false); const [confirm, setConfirm] = useState<{ purge: boolean } | null>(null); const [typed, setTyped] = useState('');
  const config = server.config ?? {};
  const save = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget);
    try { await api<ActionResponse>(`/api/v1/servers/${server.id}/config`, { method: 'PUT', body: JSON.stringify({ motd: data.get('motd'), difficulty: data.get('difficulty'), gamemode: data.get('gamemode'), maxPlayers: Number(data.get('maxPlayers')), viewDistance: Number(data.get('viewDistance')), simulationDistance: Number(data.get('simulationDistance')), onlineMode: data.get('onlineMode') === 'on', whiteList: data.get('whiteList') === 'on', whiteListPlayers: data.get('whiteListPlayers') }) }); notify(tr('Konfigurasi masuk antrean dan akan diterapkan.', 'Configuration queued and will be applied.'), 'success'); await reload(); }
    catch (error) { onError(error); } finally { setBusy(false); }
  };
  const tabs: Array<{ id: SettingsTab; label: string; icon: typeof Settings2 }> = [{ id: 'general', label: tr('Umum', 'General'), icon: Settings2 }, { id: 'startup', label: tr('Startup', 'Startup'), icon: Zap }, { id: 'limits', label: tr('Batas Resource', 'Limits'), icon: Cpu }, { id: 'danger', label: tr('Zona Bahaya', 'Danger Zone'), icon: AlertTriangle }];
  return <div className="settings-layout"><nav className="settings-tabs">{tabs.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}><Icon />{label}</button>)}</nav><section className={`surface settings-content ${tab === 'danger' ? 'danger-zone' : ''}`}>
    {tab === 'general' && <form className="form-stack" onSubmit={save}><div className="section-heading"><div><h1>{tr('Pengaturan Umum', 'General Settings')}</h1><p>server.properties</p></div></div><div className="read-only-grid"><label>{tr('Nama Server', 'Server Name')}<input value={server.name} readOnly /><small>{tr('Perubahan nama belum didukung API.', 'Name updates are not supported by the API yet.')}</small></label><label>{tr('Versi Minecraft', 'Minecraft Version')}<input value={server.version} readOnly /></label></div><label>MOTD<input name="motd" defaultValue={String(config.motd ?? 'A MyPanel Minecraft Server')} /></label><div className="form-row"><label>Difficulty<select name="difficulty" defaultValue={String(config.difficulty ?? 'normal')}><option>peaceful</option><option>easy</option><option>normal</option><option>hard</option></select></label><label>Gamemode<select name="gamemode" defaultValue={String(config.gamemode ?? 'survival')}><option>survival</option><option>creative</option><option>adventure</option><option>spectator</option></select></label></div><div className="form-row"><label>Max players<input name="maxPlayers" type="number" min="1" max="1000" defaultValue={Number(config.maxPlayers ?? 20)} /></label><label>View distance<input name="viewDistance" type="number" min="2" max="32" defaultValue={Number(config.viewDistance ?? 10)} /></label></div><label>Simulation distance<input name="simulationDistance" type="number" min="2" max="32" defaultValue={Number(config.simulationDistance ?? 10)} /></label><div className="check-row"><label><input name="onlineMode" type="checkbox" defaultChecked={config.onlineMode !== false} />Online mode</label><label><input name="whiteList" type="checkbox" defaultChecked={config.whiteList === true} />Whitelist</label></div><label>Whitelist players<input name="whiteListPlayers" defaultValue={String(config.whiteListPlayers ?? '')} placeholder="Steve, Alex" /></label><ActionButton type="submit" icon={Save} loading={busy} disabled={!!server.currentJob}>{tr('Simpan dan Terapkan', 'Save and Apply')}</ActionButton></form>}
    {tab === 'startup' && <div className="settings-section"><h1>Startup</h1><p>{tr('Konfigurasi runtime ini ditentukan saat provisioning dan belum dapat diubah melalui API.', 'This runtime configuration is set during provisioning and cannot yet be changed through the API.')}</p><div className="detail-list"><div><ServerIcon /><span><small>Runtime</small><b>{server.runtime}</b></span></div><div><Zap /><span><small>Java</small><b>Java {server.javaVersion}</b></span></div><div><Settings2 /><span><small>{tr('Versi Minecraft', 'Minecraft version')}</small><b>{server.version}</b></span></div></div></div>}
    {tab === 'limits' && <div className="settings-section"><h1>{tr('Batas Resource', 'Resource Limits')}</h1><p>{tr('Nilai ini diterapkan oleh agent. Endpoint untuk mengubah limit belum tersedia.', 'These values are enforced by the agent. A limit-update endpoint is not available yet.')}</p><div className="limit-cards"><article><Cpu /><span><small>CPU</small><b>{server.cpu} vCPU</b></span></article><article><MemoryStick /><span><small>RAM</small><b>{formatBytes(server.memoryMb * 1024 * 1024)}</b></span></article><article><HardDrive /><span><small>Disk</small><b>{formatBytes(server.diskMb * 1024 * 1024)}</b></span></article></div></div>}
    {tab === 'danger' && <div className="settings-section"><AlertTriangle className="danger-icon" /><h1>{tr('Zona Bahaya', 'Danger Zone')}</h1><p>{tr('Penghapusan runtime membebaskan port. Data dapat dipertahankan untuk pemulihan manual atau dihapus permanen.', 'Deleting the runtime releases its port. Data can be retained for manual recovery or permanently removed.')}</p><div className="danger-actions"><div><b>{tr('Hapus runtime', 'Delete runtime')}</b><small>{tr('Pertahankan world dan file server.', 'Keep the server world and files.')}</small><ActionButton variant="danger" icon={Trash2} disabled={!!server.currentJob} onClick={() => setConfirm({ purge: false })}>{tr('Hapus, pertahankan data', 'Delete, retain data')}</ActionButton></div><div><b>{tr('Hapus seluruh data', 'Delete all data')}</b><small>{tr('World, konfigurasi, dan file akan hilang permanen.', 'World, configuration, and files will be permanently removed.')}</small><ActionButton variant="danger" icon={Trash2} disabled={!!server.currentJob} onClick={() => setConfirm({ purge: true })}>{tr('Hapus permanen', 'Delete permanently')}</ActionButton></div></div></div>}
  </section><Modal open={!!confirm} onClose={() => { setConfirm(null); setTyped(''); }} title={confirm?.purge ? tr('Hapus seluruh data?', 'Delete all data?') : tr('Hapus server?', 'Delete server?')} footer={<><ActionButton variant="secondary" onClick={() => setConfirm(null)}>{tr('Batal', 'Cancel')}</ActionButton><ActionButton variant="danger" loading={busy} disabled={typed !== server.name} onClick={async () => { if (!confirm) return; setBusy(true); try { await remove(server, confirm.purge); setConfirm(null); } finally { setBusy(false); } }}>{tr('Konfirmasi Hapus', 'Confirm Delete')}</ActionButton></>}><p>{tr(`Ketik nama server “${server.name}” untuk melanjutkan.`, `Type the server name “${server.name}” to continue.`)}</p><label>{tr('Nama server', 'Server name')}<input value={typed} onChange={(event) => setTyped(event.target.value)} autoComplete="off" /></label></Modal></div>;
}
